sudo: false
language: perl
perl:
   - "blead"
   - "5.20"
   - "5.18"
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"
   - "5.8"

matrix:
  allow_failures:
    - perl: "blead"

before_install:
   - git clone git://github.com/haarg/perl-travis-helper
   - source perl-travis-helper/init
   - build-perl
   - perl -V

install:
  - cpanm -nq --installdeps .
  - cpanm -nq Devel::Cover::Report::Coveralls
script:
   - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv t
   - cover
after_success:
  - cover -report coveralls
