sudo: true
language: perl
matrix:
  include:
    # slowest to fastest
    - perl: blead
    - perl: 5.18
      env: COVERAGE=1
    - perl: 5.10
    - perl: 5.14
    - perl: 5.26
  allow_failures:
    - perl: blead
before_install:
  - sudo apt-get update
  - sudo apt-get install ditaa
  - eval $(curl https://travis-perl.github.io/init) --auto
